import { Card, FrequencySound, NatureSound, Theme, PetType } from './types';

export const COLORS = {
  bg: '#F8F9FA',
  lavender: 'rgba(167, 139, 250, 0.9)', // Violet 400
  peach: 'rgba(251, 146, 60, 0.9)',    // Orange 400
  mint: 'rgba(52, 211, 153, 0.9)',     // Emerald 400
  sky: 'rgba(56, 189, 248, 0.9)',      // Sky 400
  rose: 'rgba(251, 113, 133, 0.9)',     // Rose 400
  amber: 'rgba(251, 191, 36, 0.9)',    // Amber 400
  indigo: 'rgba(129, 140, 248, 0.9)',  // Indigo 400
  teal: 'rgba(45, 212, 191, 0.9)',     // Teal 400
  fuchsia: 'rgba(232, 121, 249, 0.9)', // Fuchsia 400
  lime: 'rgba(163, 230, 53, 0.9)',     // Lime 400
  primary: '#8A2BE2',
  secondary: '#FF7F50',
};

const COLOR_LIST = [
  COLORS.lavender, COLORS.peach, COLORS.mint, COLORS.sky, COLORS.rose,
  COLORS.amber, COLORS.indigo, COLORS.teal, COLORS.fuchsia, COLORS.lime
];

export const THEMES: Theme[] = [
  { id: 'default', name: 'Varsayılan', price: 0, type: 'color', value: '#F8F9FA', preview: '#F8F9FA' },
  { id: 'lavender_theme', name: 'Lavanta', price: 50, type: 'color', value: '#F3E8FF', preview: '#F3E8FF' },
  { id: 'mint_theme', name: 'Nane', price: 50, type: 'color', value: '#ECFDF5', preview: '#ECFDF5' },
  { id: 'sunset_theme', name: 'Gün Batımı', price: 50, type: 'color', value: '#FFF7ED', preview: '#FFF7ED' },
  { id: 'ocean_theme', name: 'Okyanus', price: 50, type: 'color', value: '#F0F9FF', preview: '#F0F9FF' },
  { id: 'rose_theme', name: 'Gül Kurusu', price: 50, type: 'color', value: '#FFF1F2', preview: '#FFF1F2' },
  { id: 'amber_theme', name: 'Kehribar', price: 50, type: 'color', value: '#FFFBEB', preview: '#FFFBEB' },
  { id: 'slate_theme', name: 'Arduvaz', price: 50, type: 'color', value: '#F8FAFC', preview: '#F8FAFC' },
  { id: 'theme-7', name: 'Gece Mavisi', price: 50, type: 'color', value: '#1e3a8a', preview: '#1e3a8a' },
  { id: 'theme-8', name: 'Zümrüt', price: 50, type: 'color', value: '#065f46', preview: '#065f46' },
  { id: 'theme-9', name: 'Altın Gün', price: 100, type: 'image', value: 'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=1000&q=80', preview: 'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=200&q=80' },
  { id: 'theme-10', name: 'Yıldızlı Gece', price: 100, type: 'image', value: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?auto=format&fit=crop&w=1000&q=80', preview: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?auto=format&fit=crop&w=200&q=80' },
  { id: 'theme-11', name: 'Sisli Orman', price: 100, type: 'image', value: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1000&q=80', preview: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=200&q=80' },
  { id: 'theme-12', name: 'Okyanus Esintisi', price: 100, type: 'image', value: 'https://images.unsplash.com/photo-1505118380757-91f5f45d8de4?auto=format&fit=crop&w=1000&q=80', preview: 'https://images.unsplash.com/photo-1505118380757-91f5f45d8de4?auto=format&fit=crop&w=200&q=80' },
  { id: 'forest_theme', name: 'Orman Esintisi', price: 100, type: 'image', value: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1000&q=80', preview: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=200&q=80' },
  { id: 'stars_theme', name: 'Yıldızlı Gece 2', price: 100, type: 'image', value: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?auto=format&fit=crop&w=1000&q=80', preview: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?auto=format&fit=crop&w=200&q=80' },
  { id: 'zen_theme', name: 'Zen Bahçesi', price: 100, type: 'image', value: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1000&q=80', preview: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=200&q=80' },
];

export const PET_OPTIONS: { type: PetType; emoji: string; label: string; description: string; image: string; price: number }[] = [
  { 
    type: 'cat', 
    emoji: '🐱', 
    label: 'Kedi', 
    description: 'Sessiz ve huzurlu bir dost. Seninle meditasyon yapmayı sever.',
    image: 'https://raw.githubusercontent.com/Ahmetbhdrr/Hayat-Enerjjisi/main/IMG_SEGMENT_20260322_133234.png',
    price: 0
  },
  { 
    type: 'dog', 
    emoji: '🐶', 
    label: 'Köpek', 
    description: 'Enerjik ve sadık. Seni her zaman neşelendirir.',
    image: 'https://raw.githubusercontent.com/Ahmetbhdrr/Hayat-Enerjjisi/main/IMG_SEGMENT_20260322_133243.png',
    price: 20
  },
  { 
    type: 'rabbit', 
    emoji: '🐰', 
    label: 'Tavşan', 
    description: 'Hızlı ve meraklı. Yeni şeyler keşfetmene yardımcı olur.',
    image: 'https://raw.githubusercontent.com/Ahmetbhdrr/Hayat-Enerjjisi/main/IMG_SEGMENT_20260322_133300.png',
    price: 20
  },
  { 
    type: 'panda', 
    emoji: '🐼', 
    label: 'Panda', 
    description: 'Sakin ve bilge. Hayata daha geniş bir açıdan bakmanı sağlar.',
    image: 'https://raw.githubusercontent.com/Ahmetbhdrr/Hayat-Enerjjisi/main/IMG_SEGMENT_20260322_133249.png',
    price: 20
  },
  { 
    type: 'fox', 
    emoji: '🦊', 
    label: 'Tilki', 
    description: 'Zeki ve çevik. Sorunlara yaratıcı çözümler bulmanı sağlar.',
    image: 'https://raw.githubusercontent.com/Ahmetbhdrr/Hayat-Enerjjisi/main/IMG_SEGMENT_20260322_133254.png',
    price: 30
  },
  { 
    type: 'koala', 
    emoji: '🐨', 
    label: 'Koala', 
    description: 'Rahat ve huzurlu. Dinlenmenin önemini hatırlatır.',
    image: 'https://raw.githubusercontent.com/Ahmetbhdrr/Hayat-Enerjjisi/main/IMG_SEGMENT_20260322_133520.png',
    price: 30
  }
];

export const OUTFITS = [
  { id: 'default', name: 'Doğal', emoji: '✨', price: 0 },
  { id: 'hat', name: 'Şapka', emoji: '🎩', price: 10 },
  { id: 'glasses', name: 'Gözlük', emoji: '👓', price: 10 },
  { id: 'bowtie', name: 'Papyon', emoji: '🎀', price: 10 },
  { id: 'crown', name: 'Taç', emoji: '👑', price: 15 },
  { id: 'scarf', name: 'Atkı', emoji: '🧣', price: 10 },
  { id: 'cape', name: 'Pelerin', emoji: '🦸‍♂️', price: 20 },
  { id: 'medal', name: 'Madalya', emoji: '🏅', price: 15 }
];

export const MOTIVATION_CARDS: Card[] = [
  { id: 'm1', content: "Her gün yeni bir başlangıçtır. Dün ne olursa olsun, bugün her şeyi değiştirebilirsin.", type: 'motivation', color: COLORS.lavender },
  { id: 'm2', content: "Zorluklar, seni daha güçlü kılmak için vardır.", type: 'motivation', color: COLORS.peach },
  { id: 'm3', content: "İçindeki güce inan, o her şeyi başarabilir.", type: 'motivation', color: COLORS.mint },
  { id: 'm4', content: "Küçük adımlar, büyük değişimlerin habercisidir.", type: 'motivation', color: COLORS.sky },
  { id: 'm5', content: "Bugün kendin için bir iyilik yap.", type: 'motivation', color: COLORS.rose },
  { id: 'm6', content: "Başarı, hazırlık ve fırsatın buluştuğu noktadır.", type: 'motivation', color: COLORS.amber },
  { id: 'm7', content: "Yolculuk, varış noktasından daha önemlidir.", type: 'motivation', color: COLORS.indigo },
  { id: 'm8', content: "Korkularının üzerine git, onlar sadece birer illüzyon.", type: 'motivation', color: COLORS.teal },
  { id: 'm9', content: "Disiplin, hedeflerle başarı arasındaki köprüdür.", type: 'motivation', color: COLORS.fuchsia },
  { id: 'm10', content: "En büyük zafer, hiç düşmemek değil, her düştüğünde kalkabilmektir.", type: 'motivation', color: COLORS.lime },
  { id: 'm11', content: "Hayallerin, senin gelecekteki gerçekliğinin fragmanlarıdır.", type: 'motivation', color: COLORS.lavender },
  { id: 'm12', content: "Zamanını başkalarının hayatını yaşayarak harcama.", type: 'motivation', color: COLORS.peach },
  { id: 'm13', content: "Zor yollar genellikle güzel manzaralara çıkar.", type: 'motivation', color: COLORS.mint },
  { id: 'm14', content: "Kendine inanmaya başladığında, mucizeler gerçekleşmeye başlar.", type: 'motivation', color: COLORS.sky },
  { id: 'm15', content: "Sadece başla. Mükemmel olmana gerek yok.", type: 'motivation', color: COLORS.rose },
  { id: 'm16', content: "Bugünkü çaban, yarınki gücündür.", type: 'motivation', color: COLORS.amber },
  { id: 'm17', content: "Engeller, gözlerini hedeften ayırdığında gördüğün korkunç şeylerdir.", type: 'motivation', color: COLORS.indigo },
  { id: 'm18', content: "Hayat, senin ona ne verdiğinle ilgilidir.", type: 'motivation', color: COLORS.teal },
  { id: 'm19', content: "Gülümse, çünkü bu dünyayı değiştirebilecek en güçlü silahtır.", type: 'motivation', color: COLORS.fuchsia },
  { id: 'm20', content: "Asla vazgeçme. Büyük şeyler zaman alır.", type: 'motivation', color: COLORS.lime },
  { id: 'm21', content: "Kendi ışığını yarat, karanlıkta yolunu bulursun.", type: 'motivation', color: COLORS.lavender },
  { id: 'm22', content: "Zirveye çıkan yol, sabırla döşenmiştir.", type: 'motivation', color: COLORS.peach },
  { id: 'm23', content: "Her fırtınadan sonra güneş açar.", type: 'motivation', color: COLORS.mint },
  { id: 'm24', content: "Sen sandığından çok daha fazlasısın.", type: 'motivation', color: COLORS.sky },
  { id: 'm25', content: "Bugün, hayatının geri kalanının ilk günü.", type: 'motivation', color: COLORS.rose },
];

export const AFFIRMATION_CARDS: Card[] = [
  { id: 'a1', content: "Ben yeterliyim.", type: 'affirmation', color: COLORS.mint },
  { id: 'a2', content: "Huzur içindeyim.", type: 'affirmation', color: COLORS.sky },
  { id: 'a3', content: "Kendimi olduğum gibi seviyorum.", type: 'affirmation', color: COLORS.rose },
  { id: 'a4', content: "Her geçen gün daha da gelişiyorum.", type: 'affirmation', color: COLORS.lavender },
  { id: 'a5', content: "Evrenin bolluk ve bereketi benimle.", type: 'affirmation', color: COLORS.peach },
  { id: 'a6', content: "Sağlıklıyım ve güçlüyüm.", type: 'affirmation', color: COLORS.amber },
  { id: 'a7', content: "Zihnim berrak ve sakin.", type: 'affirmation', color: COLORS.indigo },
  { id: 'a8', content: "Başarıya giden yolda emin adımlarla ilerliyorum.", type: 'affirmation', color: COLORS.teal },
  { id: 'a9', content: "Ben sevilmeye değerim.", type: 'affirmation', color: COLORS.fuchsia },
  { id: 'a10', content: "Hayatımın kontrolü benim elimde.", type: 'affirmation', color: COLORS.lime },
  { id: 'a11', content: "Her zorluğun üstesinden gelebilirim.", type: 'affirmation', color: COLORS.lavender },
  { id: 'a12', content: "İç huzurum her şeyden önemli.", type: 'affirmation', color: COLORS.peach },
  { id: 'a13', content: "Yaratıcılığım sınırsız.", type: 'affirmation', color: COLORS.mint },
  { id: 'a14', content: "Ben bir mıknatısım; iyilikleri kendime çekiyorum.", type: 'affirmation', color: COLORS.sky },
  { id: 'a15', content: "Geçmişi serbest bırakıyorum ve ana odaklanıyorum.", type: 'affirmation', color: COLORS.rose },
  { id: 'a16', content: "Vücuduma saygı duyuyorum ve onu besliyorum.", type: 'affirmation', color: COLORS.amber },
  { id: 'a17', content: "Her nefeste şifa buluyorum.", type: 'affirmation', color: COLORS.indigo },
  { id: 'a18', content: "Ben cesurum ve risk alabilirim.", type: 'affirmation', color: COLORS.teal },
  { id: 'a19', content: "Fikirlerim değerli ve önemli.", type: 'affirmation', color: COLORS.fuchsia },
  { id: 'a20', content: "Hayat bana her zaman en iyisini sunar.", type: 'affirmation', color: COLORS.lime },
  { id: 'a21', content: "Ben bolluk ve bereket içindeyim.", type: 'affirmation', color: COLORS.lavender },
  { id: 'a22', content: "Zihnim pozitif düşüncelerle dolu.", type: 'affirmation', color: COLORS.peach },
  { id: 'a23', content: "Kendime güveniyorum.", type: 'affirmation', color: COLORS.mint },
  { id: 'a24', content: "Her gün yeni bir mucize bekliyorum.", type: 'affirmation', color: COLORS.sky },
  { id: 'a25', content: "Ben ışığım ve parlıyorum.", type: 'affirmation', color: COLORS.rose },
  { id: 'a26', content: "Affetmeyi seçiyorum ve özgürleşiyorum.", type: 'affirmation', color: COLORS.amber },
  { id: 'a27', content: "Kendi değerimin farkındayım.", type: 'affirmation', color: COLORS.indigo },
  { id: 'a28', content: "Hayallerime ulaşmak için gereken her şeye sahibim.", type: 'affirmation', color: COLORS.teal },
  { id: 'a29', content: "Ben huzurlu bir limanım.", type: 'affirmation', color: COLORS.fuchsia },
  { id: 'a30', content: "Her şey yolunda ve ben güvendeyim.", type: 'affirmation', color: COLORS.lime },
];

export const PHYSICAL_TASKS = [
  { id: 'p1', title: "2 Litre Su İç 💧", points: 5 },
  { id: 'p2', title: "15 Dakika Yürü 🚶‍♂️", points: 15 },
  { id: 'p3', title: "Esneme Hareketleri Yap 🧘‍♀️", points: 10 },
  { id: 'p4', title: "Dik Durma Egzersizi 🧍‍♂️", points: 5 },
  { id: 'p5', title: "Güneş Işığı Al (10 dk) ☀️", points: 10 },
  { id: 'p6', title: "Meyve/Sebze Tüket 🍎", points: 10 },
  { id: 'p7', title: "Erken Uyu 😴", points: 20 },
];

export const SPIRITUAL_TASKS = [
  { id: 's1', title: "10 Dakika Meditasyon 🧘‍♂️", points: 10 },
  { id: 's2', title: "Bugün Birine İltifat Et 💬", points: 10 },
  { id: 's3', title: "Dijital Detoks (1 Saat) 📵", points: 20 },
  { id: 's4', title: "3 Şeye Şükret 🙏", points: 10 },
  { id: 's5', title: "Kitap Oku (15 dk) 📚", points: 15 },
  { id: 's6', title: "Nefes Egzersizi Yap 🌬️", points: 10 },
  { id: 's7', title: "Kendine Zaman Ayır ✨", points: 15 },
];

export const FREQUENCY_SOUNDS: FrequencySound[] = [
  { id: 'f1', name: '174 Hz', description: 'Ağrı Giderici & Güven', hz: '174', icon: '🛡️', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/174Hz.mp3', color: COLORS.lavender },
  { id: 'f2', name: '285 Hz', description: 'Hücre Yenilenmesi', hz: '285', icon: '🧬', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/285hz.mp3', color: COLORS.peach },
  { id: 'f3', name: '396 Hz', description: 'Özgürleşme', hz: '396', icon: '🔮', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/396Hz.mp3', color: '#F3E8FF' },
  { id: 'f4', name: '417 Hz', description: 'Değişimi Kolaylaştırma', hz: '417', icon: '🌀', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/417%20Hz.mp3', color: '#E0F2FE' },
  { id: 'f5', name: '432 Hz', description: 'Evrensel Uyum', hz: '432', icon: '🎵', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/432Hz%20(1).mp3', color: '#E9D5FF' },
  { id: 'f6', name: '528 Hz', description: 'Dönüşüm', hz: '528', icon: '✨', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/528Hz%20(1).mp3', color: '#D1FAE5' },
  { id: 'f7', name: '639 Hz', description: 'İlişkiler', hz: '639', icon: '💖', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/639%20Hz.mp3', color: '#FCE7F3' },
  { id: 'f8', name: '741 Hz', description: 'Sezgi', hz: '741', icon: '🌟', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/741Hz%20(1).mp3', color: '#DCFCE7' },
  { id: 'f9', name: '852 Hz', description: 'Ruhsal Uyanış', hz: '852', icon: '🧘', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/852Hz.mp3', color: '#FEE2E2' },
  { id: 'f10', name: '963 Hz', description: 'İlahi Bağlantı', hz: '963', icon: '☀️', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/963Hz.mp3', color: '#FFEDD5' },
];

export const NATURE_SOUNDS: NatureSound[] = [
  { id: 'n1', name: 'Hafif Yağmur', description: 'Zihni Sakinleştirir', icon: '🌧️', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/Ya%C4%9Fmur%20(1).mp3', color: COLORS.sky },
  { id: 'n2', name: 'Gök Gürültüsü', description: 'Güç ve Odaklanma', icon: '⛈️', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/g%C3%B6kg%C3%BCr%C3%BClt%C3%BCs%C3%BC%20(1).mp3', color: COLORS.lavender },
  { id: 'n3', name: 'Okyanus Dalgaları', description: 'Derin Gevşeme', icon: '🌊', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/DALGA%20SES%C4%B0.mp3', color: COLORS.sky },
  { id: 'n4', name: 'Orman Ambiyansı', description: 'Doğayla Bağlantı', icon: '🌳', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/Orman%20Sesleri%20(1).mp3', color: COLORS.mint },
  { id: 'n5', name: 'Dere Şırıltısı', description: 'Akışta Kalma', icon: '💧', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/%C4%B1rmak%20sesi.mp3', color: COLORS.sky },
  { id: 'n6', name: 'Tibet Çanağı', description: 'Huzurlu Uyku', icon: '🌙', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/Tibet%20%C3%A7ana%C4%9F%C4%B1.mp3', color: COLORS.rose },
  { id: 'n7', name: 'Çıtırdayan Şömine', description: 'Sıcaklık ve Güven', icon: '🔥', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/%C3%87at%C4%B1rdayan%C5%9E%C3%B6mine.mp3', color: COLORS.peach },
  { id: 'n8', name: 'Himalaya Flüt', description: 'Tazelenme', icon: '🍃', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/Himalaya%20fl%C3%BCt.mp3', color: COLORS.mint },
  { id: 'n9', name: 'Sabah Kuşları', description: 'Yeni Bir Başlangıç', icon: '🐦', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/ku%C5%9F%20sesleri%20(1).mp3', color: COLORS.sky },
  { id: 'n10', name: 'Uyku', description: 'Derin ve Deliksiz', icon: '💤', url: 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/Uyku.mp3', color: COLORS.lavender },
];

export const MYSTIC_ANSWERS = [
  "Evet", "Hayır", "Bekle", "Zamanı değil", "Tam zamanı", "Belki", "Kalbinin sesini dinle", "Doğru yoldasın",
  "Akışa bırak", "Kendine güven", "Mucizelere inan", "Sabırlı ol", "Değişim kapıda", "İçsel gücünü keşfet",
  "Evren seni destekliyor", "Şüphelerini serbest bırak", "Harekete geç", "Biraz daha düşün", "Cevap senin içinde",
  "Gülümse ve devam et", "Bu durum geçici", "Yeni bir bakış açısı geliştir", "İstediğin şey zaten seninle",
  "Biraz dinlenmeye ihtiyacın var", "Cesur ol", "Hayal kurmaktan vazgeçme", "Gerçeklik sandığından farklı",
  "Bir dostuna danış", "Kendini akışa teslim et", "Her şey olması gerektiği gibi", "Büyük bir değişim kapıda",
  "Küçük detaylara dikkat et", "İç huzurunu koru", "Cevap 'evet' ama zaman alacak", "Şu an odaklanman gereken başka bir şey var",
  "Kendine karşı dürüst ol", "Sevgiyle yaklaş", "Gereksiz yüklerinden kurtul", "Yolun açık", "Sakin kal ve gözlemle",
  "Belki de başka bir kapı açılacak", "Şansın dönmek üzere", "İnancını asla kaybetme", "Biraz daha çaba göster",
  "Hedefine çok yakınsın", "Kendini ödüllendirmeyi unutma", "Geçmişi geride bırak", "Yeni bir macera seni bekliyor",
  "Duygularını ifade et", "Zihninle kalbinin uyumunu yakala", "Her şeyin bir sebebi var", "Gelecek parlak",
  "Geri çekilip büyük resme bak", "Kendine olan sevgini artır", "Başkalarına yardım et", "Hayatın tadını çıkar",
  "Özgürlüğünü ilan et", "Kendi yolunu çiz", "Yaratıcılığını konuştur", "Huzuru kendi içinde ara",
  "Biraz sessizlik iyi gelecek", "Doğayla vakit geçir", "Yeni bir hobi edin", "Eski alışkanlıklarından kurtul",
  "Kendini keşfetme yolculuğuna çık", "Hayatın sürprizlerine açık ol", "Her gün yeni bir fırsattır",
  "Gülümsemenin gücüne inan", "Sevgi her kapıyı açar", "Kendine zaman ayır", "Ruhunu besle", "Zihnini boşalt",
  "Hayallerinin peşinden git", "Asla pes etme", "Başarı seninle olacak", "Güçlü kal", "Mutluluğu seç",
  "Pozitif düşün", "İyilik yap, iyilik bul", "Hayat güzeldir", "Her anın kıymetini bil", "Kendini sev",
  "Başkalarını affet", "Şükretmeyi unutma", "Evrenin sesini duy", "Işığını yansıt", "Kendi kahramanın ol",
  "Yolculuğun tadını çıkar", "Zirveye odaklan", "Engelleri aş", "Korkularını yen", "Cesur adımlar at",
  "Değişimi kucakla", "Yenilenme vakti", "Enerjini yükselt", "Dengede kal", "Odaklan", "Kararlı ol",
  "Disiplinli çalış", "Başarıya odaklan", "Kendini geliştir", "Öğrenmeye devam et", "Bilgi güçtür",
  "Zekanı kullan", "Stratejik düşün", "Planlı hareket et", "Zamanı iyi yönet", "Önceliklerini belirle",
  "Verimli ol", "Üretken kal", "Yaratıcı çözümler bul", "İnovatif ol", "Liderlik et", "İlham ver",
  "Motivasyonunu koru", "Tutkuyla çalış", "Amacını belirle", "Vizyon sahibi ol", "Misyonunu tamamla",
  "Değerlerine sahip çık", "Dürüstlükten ayrılma", "Adaletli ol", "Merhametli davran", "Empati kur",
  "Anlayışlı ol", "Hoşgörülü kal", "Sabırla bekle", "Azimle devam et", "Kararlılıkla ilerle", "İnançla yürü",
  "Umutla bak", "Sevgiyle yaşa", "Huzurla uyu", "Mutlulukla uyan", "Neşeyle dol", "Coşkuyla hareket et",
  "Heyecanını kaybetme", "Meraklı ol", "Keşfetmeye devam et", "Kendini tanı", "Potansiyelini fark et",
  "Yeteneklerini kullan", "Becerilerini geliştir", "Uzmanlaş", "Usta ol", "Mükemmelliği ara", "Kaliteye önem ver",
  "Detayları kaçırma", "Büyük düşün", "Sınırlarını zorla", "Konfor alanından çık", "Risk al", "Fırsatları değerlendir",
  "Zamanı yakala", "Anı yaşa", "Geleceği inşa et", "Geçmişten ders al", "Tecrübelerini paylaş", "Bilgeliğe ulaş",
  "Aydınlan", "Farkındalığını artır", "Bilinçli ol", "Uyanık kal", "Dikkatli ol", "Tedbirli davran", "Öngörülü ol",
  "Sezgilerine güven", "İçgüdülerini dinle", "Ruhuna kulak ver", "Kalbinin ritmini duy", "Evrenle bir ol",
  "Doğayla uyum sağla", "Hayvanları sev", "Bitkileri koru", "Dünyaya saygı duy", "Çevreni temiz tut",
  "Sürdürülebilir yaşa", "Tasarruflu ol", "İsraftan kaçın", "Paylaşımcı ol", "Yardımsever kal", "Dayanışma içinde ol",
  "Birlik ol", "Beraberlikten güç al", "Barışçıl ol", "Çatışmadan kaçın", "Uzlaşmacı davran", "Diplomatik ol",
  "Nezaketli davran", "Kibar ol", "Saygılı kal", "Edeple yaşa", "Ahlaklı ol", "Erdemli kal", "Yüce gönüllü ol",
  "Alçakgönüllü davran", "Mütevazı ol", "Sade yaşa", "Minimalist ol", "Özgün kal", "Kendin ol", "Taklit etme",
  "Yaratıcı ol", "Sanatla ilgilen", "Müzik dinle", "Resim yap", "Yazı yaz", "Şiir oku", "Dans et", "Spor yap",
  "Sağlıklı beslen", "Bol su iç", "Düzenli uyu", "Meditasyon yap", "Yoga yap", "Nefes egzersizi yap", "Zihnini dinlendir",
  "Ruhunu arındır", "Bedenine iyi bak", "Kendine değer ver", "Hayatını sev", "Dünyayı gez", "Yeni yerler gör",
  "Yeni insanlar tanı", "Farklı kültürleri keşfet", "Dil öğren", "Kitap oku", "Film izle", "Tiyatroya git",
  "Konsere git", "Sergileri gez", "Bilimle ilgilen", "Teknolojiyi takip et", "Geleceğe hazırlan", "Değişime ayak uydur",
  "Esnek ol", "Uyumlu kal", "Dayanıklı ol", "Güçlü kal", "Yılmaz ol", "Cesur ol", "Kahraman ol", "Efsane ol",
  "İz bırak", "Fark yarat", "Dünyayı değiştir", "İyiliği yay", "Sevgiyi paylaş", "Işık ol", "Umut ol", "Hayat ol",
  "Aşk ol", "Huzur ol", "Mutluluk ol", "Sen ol", "Tam zamanı", "Vaktini bekle", "Zamana bırak", "Kalbinden geçeni yap",
  "Doğru yoldasın", "Olabilir", "Belki", "Hayır", "Evet", "Kesinlikle", "Asla", "Şimdi değil", "Biraz daha bekle",
  "Hemen harekete geç", "Gözlerini aç", "Fırsatı kaçırma", "Dikkatli bak", "Cevap çok yakın", "Gülümse ve bekle",
  "Her şey yoluna girecek", "Yıldızlar seninle", "Kendi mucizeni yarat", "Işığını takip et", "Yolun sonu aydınlık",
  "Biraz daha sabır", "Şimdi tam sırası", "Gönlünden geçeni yap", "Evrenin fısıltısını duy", "Kendi gerçeğini yaşa",
  "Başarı kapıda", "Sevgiyle kal", "Huzuru bul", "Kendine inan", "Gücünü fark et", "Yolun açık olsun", "Mutlu ol",
  "Gülümse", "İnan", "Başar", "Sev", "Yaşa", "Hisset", "Gör", "Duy", "Bil", "Ol"
];

export const BACKGROUND_MUSIC_URL = 'https://github.com/Ahmetbhdrr/Hayat-Enerjjisi/raw/refs/heads/main/backgroundsound.mp3';

export const ANSWERS = [
  "Sabret, doğru zaman yaklaşıyor.",
  "İçindeki sesi dinle, o cevabı biliyor.",
  "Evren seni destekliyor, korkma.",
  "Şu an için en iyisi beklemek.",
  "Evet, kesinlikle doğru yoldasın.",
  "Hayır, bu yol senin için uygun değil.",
  "Mucizelere hazır ol.",
  "Kendine daha fazla güvenmelisin.",
  "Cevap senin kalbinde saklı.",
  "Zaman her şeyi gösterecek.",
  "Şüphelerini bir kenara bırak.",
  "Beklenmedik bir yerden yardım gelecek.",
  "Harekete geçmek için mükemmel bir an.",
  "Biraz daha derinlemesine düşün.",
  "Başkalarının fikirlerine kulak ver.",
  "Sadece akışa bırak.",
  "Sonuç seni şaşırtacak.",
  "Daha fazla bilgiye ihtiyacın var.",
  "Cömert ol, karşılığını alacaksın.",
  "Gülümse ve devam et.",
  "Bu durum geçici, sabırlı ol.",
  "Yeni bir bakış açısı geliştir.",
  "İstediğin şey zaten seninle.",
  "Biraz dinlenmeye ihtiyacın var.",
  "Cesur ol, ödülün büyük olacak.",
  "Hayal kurmaktan vazgeçme.",
  "Gerçeklik sandığından daha farklı.",
  "Bir dostuna danış.",
  "Kendini akışa teslim et.",
  "Her şey olması gerektiği gibi.",
  "Büyük bir değişim kapıda.",
  "Küçük detaylara dikkat et.",
  "İç huzurunu koru.",
  "Cevap 'evet' ama biraz zaman alacak.",
  "Şu an odaklanman gereken başka bir şey var.",
  "Kendine karşı dürüst ol.",
  "Sevgiyle yaklaş, her şey çözülecek.",
  "Gereksiz yüklerinden kurtul.",
  "Yolun açık, ilerle.",
  "Sakin kal ve gözlemle.",
  "Belki de başka bir kapı açılacak.",
  "Şansın dönmek üzere.",
  "İnancını asla kaybetme.",
  "Biraz daha çaba göstermelisin.",
  "Hedefine çok yakınsın.",
  "Kendini ödüllendirmeyi unutma.",
  "Geçmişi geride bırakma vakti.",
  "Yeni bir macera seni bekliyor.",
  "Duygularını ifade etmekten çekinme.",
  "Zihninle kalbinin uyumunu yakala.",
  "Her şeyin bir sebebi var.",
  "Gelecek parlak görünüyor.",
  "Biraz geri çekilip büyük resme bak.",
  "Kendine olan sevgini artır.",
  "Başkalarına yardım etmek sana iyi gelecek.",
  "Hayatın tadını çıkar.",
  "Özgürlüğünü ilan et.",
  "Kendi yolunu kendin çiz.",
  "Yaratıcılığını konuştur.",
  "Huzuru kendi içinde ara.",
  "Biraz sessizlik sana iyi gelecek.",
  "Doğayla vakit geçir.",
  "Yeni bir hobi edin.",
  "Eski alışkanlıklarından kurtul.",
  "Kendini keşfetme yolculuğuna çık.",
  "Hayatın sürprizlerine açık ol.",
  "Her gün yeni bir fırsattır.",
  "Gülümsemenin gücüne inan.",
  "Sevgi her kapıyı açar.",
  "Kendine zaman ayır.",
  "Ruhunu besle.",
  "Zihnini boşalt.",
  "Kalbinin sesini dinle.",
  "Hayallerinin peşinden git.",
  "Asla pes etme.",
  "Başarı seninle olacak.",
  "Kendine güven.",
  "Güçlü kal.",
  "Sabırlı ol.",
  "Mutluluğu seç.",
  "Pozitif düşün.",
  "İyilik yap, iyilik bul.",
  "Hayat güzeldir.",
  "Her anın kıymetini bil.",
  "Kendini sev.",
  "Başkalarını affet.",
  "Şükretmeyi unutma.",
  "Mucizelere inan.",
  "Evrenin sesini duy.",
  "Işığını yansıt.",
  "Kendi kahramanın ol.",
  "Yolculuğun tadını çıkar.",
  "Zirveye odaklan.",
  "Engelleri aş.",
  "Korkularını yen.",
  "Cesur adımlar at.",
  "Değişimi kucakla.",
  "Yenilenme vakti.",
  "Enerjini yükselt.",
  "Dengede kal.",
  "Odaklan.",
  "Kararlı ol.",
  "Disiplinli çalış.",
  "Başarıya odaklan.",
  "Kendini geliştir.",
  "Öğrenmeye devam et.",
  "Bilgi güçtür.",
  "Zekanı kullan.",
  "Stratejik düşün.",
  "Planlı hareket et.",
  "Zamanı iyi yönet.",
  "Önceliklerini belirle.",
  "Verimli ol.",
  "Üretken kal.",
  "Yaratıcı çözümler bul.",
  "İnovatif ol.",
  "Girişimci ruhunu ortaya çıkar.",
  "Liderlik et.",
  "İlham ver.",
  "Motivasyonunu koru.",
  "Tutkuyla çalış.",
  "Amacını belirle.",
  "Vizyon sahibi ol.",
  "Misyonunu tamamla.",
  "Değerlerine sahip çık.",
  "Dürüstlükten ayrılma.",
  "Adaletli ol.",
  "Merhametli davran.",
  "Empati kur.",
  "Anlayışlı ol.",
  "Hoşgörülü kal.",
  "Sabırla bekle.",
  "Azimle devam et.",
  "Kararlılıkla ilerle.",
  "İnançla yürü.",
  "Umutla bak.",
  "Sevgiyle yaşa.",
  "Huzurla uyu.",
  "Mutlulukla uyan.",
  "Neşeyle dol.",
  "Coşkuyla hareket et.",
  "Heyecanını kaybetme.",
  "Meraklı ol.",
  "Keşfetmeye devam et.",
  "Öğrenmekten vazgeçme.",
  "Kendini tanı.",
  "Potansiyelini fark et.",
  "Yeteneklerini kullan.",
  "Becerilerini geliştir.",
  "Uzmanlaş.",
  "Usta ol.",
  "Mükemmelliği ara.",
  "Kaliteye önem ver.",
  "Detayları kaçırma.",
  "Büyük düşün.",
  "Sınırlarını zorla.",
  "Konfor alanından çık.",
  "Risk al.",
  "Fırsatları değerlendir.",
  "Zamanı yakala.",
  "Anı yaşa.",
  "Geleceği inşa et.",
  "Geçmişten ders al.",
  "Tecrübelerini paylaş.",
  "Bilgeliğe ulaş.",
  "Aydınlan.",
  "Farkındalığını artır.",
  "Bilinçli ol.",
  "Uyanık kal.",
  "Dikkatli ol.",
  "Tedbirli davran.",
  "Öngörülü ol.",
  "Sezgilerine güven.",
  "İçgüdülerini dinle.",
  "Ruhuna kulak ver.",
  "Kalbinin ritmini duy.",
  "Evrenle bir ol.",
  "Doğayla uyum sağla.",
  "Hayvanları sev.",
  "Bitkileri koru.",
  "Dünyaya saygı duy.",
  "Çevreni temiz tut.",
  "Sürdürülebilir yaşa.",
  "Tasarruflu ol.",
  "İsraftan kaçın.",
  "Paylaşımcı ol.",
  "Yardımsever kal.",
  "Dayanışma içinde ol.",
  "Birlik ol.",
  "Beraberlikten güç al.",
  "Barışçıl ol.",
  "Çatışmadan kaçın.",
  "Uzlaşmacı davran.",
  "Diplomatik ol.",
  "Nezaketli davran.",
  "Kibar ol.",
  "Saygılı kal.",
  "Edeple yaşa.",
  "Ahlaklı ol.",
  "Erdemli kal.",
  "Yüce gönüllü ol.",
  "Alçakgönüllü davran.",
  "Mütevazı ol.",
  "Sade yaşa.",
  "Minimalist ol.",
  "Özgün kal.",
  "Kendin ol.",
  "Taklit etme.",
  "Yaratıcı ol.",
  "Sanatla ilgilen.",
  "Müzik dinle.",
  "Resim yap.",
  "Yazı yaz.",
  "Şiir oku.",
  "Dans et.",
  "Spor yap.",
  "Sağlıklı beslen.",
  "Bol su iç.",
  "Düzenli uyu.",
  "Meditasyon yap.",
  "Yoga yap.",
  "Nefes egzersizi yap.",
  "Zihnini dinlendir.",
  "Ruhunu arındır.",
  "Bedenine iyi bak.",
  "Kendine değer ver.",
  "Hayatını sev.",
  "Dünyayı gez.",
  "Yeni yerler gör.",
  "Yeni insanlar tanı.",
  "Farklı kültürleri keşfet.",
  "Dil öğren.",
  "Kitap oku.",
  "Film izle.",
  "Tiyatroya git.",
  "Konsere git.",
  "Sergileri gez.",
  "Bilimle ilgilen.",
  "Teknolojiyi takip et.",
  "Geleceğe hazırlan.",
  "Değişime ayak uydur.",
  "Esnek ol.",
  "Uyumlu kal.",
  "Dayanıklı ol.",
  "Güçlü kal.",
  "Yılmaz ol.",
  "Cesur ol.",
  "Kahraman ol.",
  "Efsane ol.",
  "İz bırak.",
  "Fark yarat.",
  "Dünyayı değiştir.",
  "İyiliği yay.",
  "Sevgiyi paylaş.",
  "Işık ol.",
  "Umut ol.",
  "Hayat ol.",
  "Aşk ol.",
  "Huzur ol.",
  "Mutluluk ol.",
  "Sen ol.",
  "Tam zamanı.",
  "Vaktini bekle.",
  "Zamana bırak.",
  "Kalbinden geçeni yap.",
  "Doğru yoldasın.",
  "Olabilir.",
  "Belki.",
  "Hayır.",
  "Evet.",
  "Kesinlikle.",
  "Asla.",
  "Şimdi değil.",
  "Biraz daha bekle.",
  "Hemen harekete geç.",
  "Gözlerini aç.",
  "Fırsatı kaçırma.",
  "Dikkatli bak.",
  "Cevap çok yakın.",
  "Gülümse ve bekle.",
  "Her şey yoluna girecek.",
];
